name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a delay
        run: |
          echo "Starting a delay..."
          sleep 30
          echo "It's been 30 seconds"
          sleep 30
          echo "It's been 60 seconds"
          sleep 30
          echo "It's been 90 seconds"
          sleep 30
          echo "It's been 120 seconds"
          sleep 30
          echo "It's been 150 seconds"
          sleep 30
          echo "It's been 180 seconds - Workflow complete"
